module Main where

import Prelude hiding (sin, cos, gcd)
import Task1_2 (sin, cos, pow, isPrime, gcd)

main :: IO ()
main = do
    putStrLn (show (pow (-1) 10))
    putStrLn (show (pow 3 3))
    putStrLn (show (sin 0.78539816339))
    putStrLn (show (cos 0.78539816339))
    putStrLn (show (isPrime 1))
    putStrLn (show (isPrime 2))
    putStrLn (show (isPrime 3))
    putStrLn (show (isPrime 4))
    putStrLn (show (isPrime 5))
    putStrLn (show (isPrime 6))
    putStrLn (show (isPrime 7))
    putStrLn (show (isPrime 8))
    putStrLn (show (isPrime 9))
    putStrLn (show (isPrime 10))
    putStrLn (show (isPrime 11))
    putStrLn (show (isPrime 21))
    putStrLn (show (isPrime 31))
    putStrLn (show (isPrime 41))
    putStrLn (show (isPrime 111))
    putStrLn (show (gcd 50 130))
    putStrLn (show (gcd 130 50))
    putStrLn (show (gcd 111 41))
    putStrLn (show (gcd 31 41))
    putStrLn (show (gcd 80 20))
    putStrLn (show (gcd 30 18))
    putStrLn (show (gcd 18 30))